/*
Informatica Job Group Name : EDW_CX_TELE_APPD_HI
Informatica Job Name : wf_SS2BR_N_TELEMETRY_APPDYNAMICS_DPLYMNT
Target Table Name : RPUTTI_N_TELEMETRY_APPDYNAMICS_DPLYMNT
*/

{{ config(materialized='incremental', 
tags='EDW_CX_TELE_APPD_HI',
sql_header='USE WAREHOUSE EDW_I_TELMTRY_CDPTELE_WH;',
database='EDW_TELMTRY_ETL_DB_DV1',
schema='W', 
allow_data_type_changes=False
) }}

{%- call statement('sqlstmt_output', fetch_result=True) -%}
    -- SELECT DISTINCT TO_CHAR(MAX(LAST_UPD_DATE),'MM/DD/YYYY HH24:MI:SS')	
	-- FROM {{source('EDW_TELMTRY_ETL_DB_SS', 'APPDYNAMICS_BASE')}}
	SELECT DISTINCT TO_CHAR(MAX(EDWSF_CREATE_DTM),'MM/DD/YYYY HH24:MI:SS')	
	FROM {{this}}
{%- endcall -%}

{%- set LastExtractDate = load_result('sqlstmt_output')['data'][0][0] -%}


SELECT
CONVERT_TIMEZONE('UTC','America/Los_Angeles', RECORDEDAT::STRING)::DATE AS SNAPSHOT_DTM,
SAAS_ACCOUNT_ID	AS SAAS_ACCOUNT_ID,
SFDC_ACCOUNT_ID	AS SFDC_ACCOUNT_ID,
TOTAL_APPLICATIONS_COUNT AS TOTAL_APPLICATIONS_CNT,
TOTAL_MONTHLY_LOGIN_COUNT	AS TOTAL_MONTHLY_LOGIN_CNT,
TOTAL_BUSINESS_TX_RULE_COUNT AS TOTAL_BSNS_TRANS_RULES_CNT,
TOTAL_BACKEND_DETECTION_RULE_COUNT	AS TOTAL_BACKND_DETECTN_RULE_CNT,
TOTAL_ERR_DETECTION_RULE_COUNT	AS TOTAL_ERROR_DETECTN_RULE_CNT,
TOTAL_SERVICE_DETECTION_RULE_COUNT	AS TOTAL_SERVICE_DETECTN_RULE_CNT,
TOTAL_CONFIGURED_USERS_COUNT	AS TOTAL_CONFIGURED_USERS_CNT,
TOTAL_APM_AGENT_COUNT	AS TOTAL_APPL_PERF_MNGMNT_AGNT_CNT,
TOTAL_BUSINESS_TX_COUNT	AS TOTAL_BSNS_TRANSACTION_CNT,
TOTAL_HEALTH_RULE_COUNT	AS TOTAL_HEALTH_RULE_CNT,
TOTAL_DATA_COLLECTOR_COUNT	AS TOTAL_DATA_COLLECTOR_CNT,
TOTAL_DASHBOARD_WIDGET_COUNT AS TOTAL_DASHBOARD_WIDGET_CNT,
TOTAL_DB_AGENT_COLLECTOR_COUNT AS TOTAL_DB_AGNT_COLLECTOR_CNT,
TOTAL_MACHINE_AGENT_COUNT AS TOTAL_MACHINE_AGNT_CNT,
TOTAL_DIAGNOSTIC_SESS_COUNT AS TOTAL_DIAGNOSTIC_SESSION_CNT,
TOTAL_CUSTOM_ACTIONS AS TOTAL_CUSTOMS_ACTIONS_CNT,
IS_BT_THRESHOLD_OPTIMIZED AS BSNS_TRANS_TRESHHOLD_OPTMZD_FLG,--boolean
CISCO_PARTY_ID	AS CUSTOMER_PARTY_KEY,
TO_NUMBER(TO_CHAR(CURRENT_TIMESTAMP()::TIMESTAMP_NTZ(9), 'YYYYMMDDHH24MISS')) AS EDWSF_BATCH_ID,
CAST(CURRENT_TIMESTAMP AS TIMESTAMP_NTZ(9)) AS EDWSF_CREATE_DTM,
CURRENT_USER() AS EDWSF_CREATE_USER,
CAST(CURRENT_TIMESTAMP AS TIMESTAMP_NTZ(9)) AS EDWSF_UPDATE_DTM,
CURRENT_USER() AS EDWSF_UPDATE_USER,
'N' AS EDWSF_SOURCE_DELETED_FLAG ,
CAST('3500-01-01 00:00:00' AS TIMESTAMP_NTZ(0)) AS EDWSF_DELETE_PROCESSED_DTM	,
TOTAL_POLICY_COUNT AS TOTAL_POLICY_CNT,
TOTAL_ACTION_COUNT AS TOTAL_ACTION_CNT,
CAST (MAX_LICENSE_EXPIRATION AS TIMESTAMP_NTZ(9)) AS MAX_LICENSE_EXPIRATION_DTM,
CAST (TELEMETRY_LAST_RECEIVED AS TIMESTAMP_NTZ(9)) AS TELEMTRY_LAST_RCVD_BY_APPD_DTM
FROM 
	{{source('EDW_TELMTRY_ETL_DB_SS', 'APPDYNAMICS_BASE')}}
WHERE SNAPSHOT_DTM > COALESCE(CAST(split_part('{{ LastExtractDate}}', '.', 1) AS TIMESTAMP), '1900-01-01 00:00:00')