version: 2

sources:
  - name: TELMTRY_ETL_DB_W
    description: 'EDW_TELMTRY_ETL_DB_DV1.W'
    database: EDW_TELMTRY_ETL_DB_DV1
    schema: W
    tables:
      - name: CSDF_TTM_PARAMETER
        description : 'TTM Parameter Table'
      - name: CSDF_TTM_META_RULE_DEFN
        description : 'TTM Rule Definition Table'
  
  - name: TELMTRY_ETL_DB_WI
    description: 'EDW_TELMTRY_ETL_DB_DV1.WI'
    database: EDW_TELMTRY_ETL_DB_DV1
    schema: WI
    tables:        
      - name: RPUTTI_CSDF_TTM_PARAMETER_APPD_TE
        description:  'TTM Parameter Table for APPD & THOUSANDEYES'
      - name: RPUTTI_CSDF_TTM_META_RULE_DEFN_APPD_TE
        description:  'TTM Rule Definition Table for APPD & THOUSANDEYES'

models:
  - name: RPUTTI_CSDF_TTM_META_RULE_DEFN_APPD
    description:  'TTM Rule Definition Table for APPD'
    columns:
      - name: THREADING_RULE_ID
        tests:
          - unique
          - not_null
      - name: THREADING_RULE_NAME
        tests:
          - not_null
