/* 
Informatica Job group name: EDW_CX_TELE_APPD_HI
Informatica wf name: wf_BR2BR_N_RT_CUST_PS_STEP_METRIC_DLY_APPD
Target table name: WI_N_RT_CUST_PS_STEP_METRIC_DLY_APPD -> N_RT_CUST_PS_STEP_METRIC_DLY
*/

{{ config(materialized = 'ephemeral'
)}}

WITH APPD_DATA AS(
    SELECT  DISTINCT 
    SNAPSHOT_DTM AS SNAPSHOT_DTM
	,SAAS_ACCOUNT_ID	AS CUSTOMER_REFERENCE_ID
	,'SAAS_ACCOUNT_ID' AS CUSTOMER_REFERENCE_TYPE
	,CAST(CUSTOMER_PARTY_KEY  AS VARCHAR) AS CISCO_PARTY_ID
	,TO_VARCHAR(COALESCE(TO_CHAR(TOTAL_APPLICATIONS_CNT),'-999')) AS TOTAL_APPLICATIONS_CNT
    ,TO_VARCHAR(COALESCE(TO_CHAR(TOTAL_MONTHLY_LOGIN_CNT),'-999')) AS TOTAL_MONTHLY_LOGIN_CNT
    ,TO_VARCHAR(COALESCE(TO_CHAR(TOTAL_BSNS_TRANS_RULES_CNT),'-999')) AS TOTAL_BSNS_TRANS_RULES_CNT
    ,TO_VARCHAR(COALESCE(TO_CHAR(TOTAL_CONFIGURED_USERS_CNT),'-999')) AS TOTAL_CONFIGURED_USERS_CNT
    ,TO_VARCHAR(COALESCE(TO_CHAR(TOTAL_APPL_PERF_MNGMNT_AGNT_CNT),'-999')) AS TOTAL_APPL_PERF_MNGMNT_AGNT_CNT
    ,TO_VARCHAR(COALESCE(TO_CHAR(TOTAL_BSNS_TRANSACTION_CNT),'-999')) AS TOTAL_BSNS_TRANSACTION_CNT
    ,TO_VARCHAR(COALESCE(TO_CHAR(TOTAL_HEALTH_RULE_CNT),'-999')) AS TOTAL_HEALTH_RULE_CNT
	,TO_VARCHAR(COALESCE(TO_CHAR(TOTAL_DATA_COLLECTOR_CNT),'-999')) AS TOTAL_DATA_COLLECTOR_CNT
	,TO_VARCHAR(COALESCE(TO_CHAR(TOTAL_DASHBOARD_WIDGET_CNT),'-999')) AS TOTAL_DASHBOARD_WIDGET_CNT
    ,TO_VARCHAR(COALESCE(TO_CHAR(TOTAL_POLICY_COUNT),'-999')) AS TOTAL_POLICY_COUNT
	,TO_VARCHAR(COALESCE(TO_CHAR(TOTAL_ACTION_COUNT),'-999')) AS TOTAL_ACTION_COUNT
    ,TO_VARCHAR(COALESCE(TO_CHAR(TOTAL_DB_AGNT_COLLECTOR_CNT),'-999')) AS TOTAL_DB_AGNT_COLLECTOR_CNT
    ,TO_VARCHAR(COALESCE(TO_CHAR(TOTAL_CUSTOMS_ACTIONS_CNT),'-999')) AS TOTAL_CUSTOMS_ACTIONS_CNT
	, CASE WHEN SAAS_ACCOUNT_ID is  NOT NULL  THEN 'YES 'ELSE 'NO' END AS IS_VALID_LICENSE
FROM
  {{source('EDW_TELMTRY_BR_DB_BR', 'N_TELEMETRY_APPDYNAMICS_DPLYMNT')}}
 		WHERE SNAPSHOT_DTM > --COALESCE(CAST(split_part('$$LastExtractDate', '.', 1) AS TIMESTAMP), '1900-01-01 00:00:00')
		(SELECT
                COALESCE(MAX(SNAPSHOT_DATE), '1900-01-01')
            FROM
                {{source('EDW_TELMTRY_BR_DB_BR', 'N_RT_CUST_PS_STEP_METRIC_DLY')}}
            WHERE
                CUSTOMER_REFERENCE_TYPE = 'SAAS_ACCOUNT_ID')
)
SELECT DISTINCT
	CUSTOMER_REFERENCE_TYPE,
	CUSTOMER_REFERENCE_ID,
    SNAPSHOT_DTM,
	METRIC_NAME,
	CASE
			WHEN METRIC_VALUE = 'UNKNOWN' THEN NULL
			ELSE METRIC_VALUE
		END AS METRIC_VALUE,  
		TO_NUMBER(TO_CHAR(CURRENT_TIMESTAMP(),
		'YYYYMMDDHH24MISS')) AS EDWSF_BATCH_ID,
		CURRENT_TIMESTAMP()::TIMESTAMP_NTZ(9) AS EDWSF_UPDATE_DTM,
		CURRENT_USER() AS EDWSF_CREATE_USER,
		CURRENT_TIMESTAMP()::TIMESTAMP_NTZ(9) AS EDWSF_CREATE_DTM,
		CURRENT_USER() AS EDWSF_UPDATE_USER,
		'N' AS EDWSF_SOURCE_DELETED_FLAG
FROM
    APPD_DATA UNPIVOT (METRIC_VALUE FOR METRIC_NAME IN (
	TOTAL_APPLICATIONS_CNT,
	TOTAL_MONTHLY_LOGIN_CNT,
	TOTAL_BSNS_TRANS_RULES_CNT,
	TOTAL_CONFIGURED_USERS_CNT,
	TOTAL_APPL_PERF_MNGMNT_AGNT_CNT,
	TOTAL_BSNS_TRANSACTION_CNT,
	TOTAL_HEALTH_RULE_CNT,
	TOTAL_DATA_COLLECTOR_CNT,
	TOTAL_DASHBOARD_WIDGET_CNT,
	TOTAL_POLICY_COUNT,
	TOTAL_ACTION_COUNT,
	TOTAL_DB_AGNT_COLLECTOR_CNT,	
	TOTAL_CUSTOMS_ACTIONS_CNT,
	IS_VALID_LICENSE
	))